service: test-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  stage: "dev"
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:899172222060:table/SwapXTable

plugins:
  - serverless-plugin-typescript
  - serverless-offline

# custom:
#   serverless-offline:
#     noPrependStageInUrl: true

functions:
  api:
    handler: src/aws/lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /api/v1
          method: ANY
          cors: true
      - http:
          path: /api/v1/{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    SwapXTable: #Resourse name(could be anything)
      Type: AWS::DynamoDB::Table #Dynamo db resourses
      Properties:
        TableName: SwapXTable #(could be anything)
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id #make id our primary key
            KeyType: HASH
