service: swapxchange-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  tags:
    service: swapxchange
  lambdaHashingVersion: "20201221"
  region: eu-west-2
  iam:
    # role: arn:aws:iam::899172222060:role/XchangeRole #Dev
    role: arn:aws:iam::100798749361:role/XchangeRole

  environment:
    NODE_OPTIONS: --enable-source-maps
  vpc:
    securityGroupIds:
      # - sg-0e16ecd2de3007de4 #Dev
      - sg-05521c3074f1dc2fd #Dev
    subnetIds:
      # - subnet-06ac3f82667ebe9f0 #Dev
      # - subnet-0f979ac6191ee988b #Dev
      # - subnet-047d66d6a250068ae #Dev
      - subnet-0d7c9144f345010d8
      - subnet-0d58d6451fa4f2daa
      - subnet-0c5be8ea063cd4adc

package:
  patterns:
    #    - '!node_modules/**' #Exclude all node_modules sub dirs
    - "src/database/**"
    - ".env"

plugins:
  #  - serverless-plugin-typescript
  - serverless-offline
#  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
#      'after:deploy:finalize': npm run db:migrate
#      'aws:deploy:finalize:cleanup': npm run db:migrate

functions:
  cli:
    handler: src/aws/lambda-cli.handler
    timeout: 300 # 5 minutes
  api:
    handler: src/aws/lambda.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /api/v1
          method: ANY
          cors: true
      - http:
          path: /api/v1/{proxy+}
          method: ANY
          cors: true
