service: test-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:899172222060:table/SwapXTable

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    # handler: src/aws/handler.hello
    events:
      - httpApi:
          path: /
          # path: /todos
          # path: /todo/{id}
          method: post

resources:
  Resources:
    SwapXTable: #Resourse name(could be anything)
      Type: AWS::DynamoDB::Table #Dynamo db resourses
      Properties:
        TableName: SwapXTable #(could be anything)
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id #make id our primary key
            KeyType: HASH
