"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = __importDefault(require("express"));
var auth_route_1 = __importDefault(require("./auth.route"));
var agora_route_1 = __importDefault(require("./agora.route"));
var category_route_1 = __importDefault(require("./category.route"));
var coins_route_1 = __importDefault(require("./coins.route"));
var faqs_route_1 = __importDefault(require("./faqs.route"));
var feedback_route_1 = __importDefault(require("./feedback.route"));
var product_chats_route_1 = __importDefault(require("./product.chats.route"));
var product_image_route_1 = __importDefault(require("./product.image.route"));
var product_route_1 = __importDefault(require("./product.route"));
var product_views_route_1 = __importDefault(require("./product.views.route"));
var reported_products_route_1 = __importDefault(require("./reported.products.route"));
var saved_products_route_1 = __importDefault(require("./saved.products.route"));
var subcategory_route_1 = __importDefault(require("./subcategory.route"));
var user_route_1 = __importDefault(require("./user.route"));
var auth_middleware_1 = require("../../middlewares/auth.middleware");
var app_settings_route_1 = __importDefault(require("./app.settings.route"));
var router = express_1.default.Router();
router.use("/auth", auth_route_1.default);
router.use("/appsettings", app_settings_route_1.default);
router.use(auth_middleware_1.requireAuth);
router.use("/users", user_route_1.default);
router.use("/agora", agora_route_1.default);
router.use("/category", category_route_1.default);
router.use("/subcategory", subcategory_route_1.default);
router.use("/productchats", product_chats_route_1.default);
router.use("/productimage", product_image_route_1.default);
router.use("/coins", coins_route_1.default);
router.use("/saved", saved_products_route_1.default);
router.use("/productviews", product_views_route_1.default);
router.use("/faqs", faqs_route_1.default);
router.use("/feedback", feedback_route_1.default);
router.use("/reportedproducts", reported_products_route_1.default);
router.use("/products", product_route_1.default);
exports.default = router;
//# sourceMappingURL=index.js.map