name: Test Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1223
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Create env file

        run: |
          cat > .env << EOF
          RSA_PUBLIC_KEY=${{ secrets.RSA_PUBLIC_KEY }}
          RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}
          NODE_ENV=test
          EOF
      - run: npm run test
