name: Prod Deploy

on:
  workflow_dispatch:

jobs:

  deploy-dev:
    name: Deploy to AWS Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Create env file

        run: |
          cat > .env << EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_NAME=${{ secrets.DB_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_ACCESS_EXPIRATION_MINUTES=${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}
          JWT_REFRESH_EXPIRATION_DAYS=${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}
          PAYSTACK_LIVE_SECRET_KEY=${{ secrets.PAYSTACK_LIVE_SECRET_KEY }}
          PAYSTACK_TEST_SECRET_KEY=${{ secrets.PAYSTACK_TEST_SECRET_KEY }}
          AGORA_APP_ID=${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERT=${{ secrets.AGORA_APP_CERT }}
          NODE_ENV=prod
          EOF


      - name: Install NPM dependencies
        run: npm install --only=prod
      # Clean redundant files in node_modules
      - run: sh "./clean.sh"
      - run: npm run build && npm run postbuild
      - name: Deploy Lambda functions (serverless deploy)
        run: cd build && serverless deploy --stage prod --region $AWS_DEFAULT_REGION

   # Run migration
      - run: sls invoke --function cli -d db:drop --stage prod --region $AWS_DEFAULT_REGION
#      - run: sls invoke --function databaseMigrations --stage prod --region $AWS_DEFAULT_REGION
      - run: sls invoke --function cli -d db:migrate --stage prod --region $AWS_DEFAULT_REGION
      - run: sls invoke --function cli -d db:seed:all --stage prod --region $AWS_DEFAULT_REGION


