name: Prod Deploy

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to AWS Prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Serverless Framework
        run: npm install -g serverless serverless-offline
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LIVE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LIVE }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Create env file

        run: |
          cat > .env << EOF
          DB_HOST=${{ secrets.DB_HOST_LIVE }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD_LIVE }}
          DB_USERNAME=${{ secrets.DB_USERNAME_LIVE }}
          DB_NAME=${{ secrets.DB_NAME_LIVE }}
          JWT_SECRET=${{ secrets.JWT_SECRET_LIVE }}
          JWT_ACCESS_EXPIRATION_MINUTES=${{ secrets.JWT_ACCESS_EXPIRATION_MINUTES }}
          JWT_REFRESH_EXPIRATION_DAYS=${{ secrets.JWT_REFRESH_EXPIRATION_DAYS }}
          PAYSTACK_LIVE_SECRET_KEY=${{ secrets.PAYSTACK_LIVE_SECRET_KEY }}
          PAYSTACK_TEST_SECRET_KEY=${{ secrets.PAYSTACK_TEST_SECRET_KEY }}
          AGORA_APP_ID=${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERT=${{ secrets.AGORA_APP_CERT }}
          RSA_PUBLIC_KEY=${{ secrets.RSA_PUBLIC_KEY_LIVE }}
          RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY_LIVE }}
          NODE_ENV=prod
          EOF

      - name: Install NPM dependencies
        run: npm install --only=prod
      - name: Clean redundant files in node_modules
        run: sh "./clean.sh"
      - name: Build ts files on build dir output
        run: npm run build && npm run postbuild
      - name: Clean redundant files(typescript module)
        run: sh "./clean.sh" # Clean redundant files again in ts build node_modules esp typescript module
      - name: Deploy Lambda functions (serverless deploy)
        run: cd build && serverless deploy --config serverless-prod.yml --stage prod --region $AWS_DEFAULT_REGION

      # Run migration
      # - run: sls invoke --function cli -d db:create --config serverless-prod.yml --stage prod --region $AWS_DEFAULT_REGION
      - run: sls invoke --function cli -d db:migrate --config serverless-prod.yml --stage prod --region $AWS_DEFAULT_REGION
