"use strict";

import { QueryInterface } from "sequelize";

export default {
  up: async ({ queryInterface }: { queryInterface: QueryInterface }) => {
    await queryInterface.bulkInsert(
      "Product",
      [
        {
          product_id: "BD9e5x3Gcpej",
          order_id: "eeppccscspa",
          product_name: "Compaq Desktop",
          category: "j9pVxA2WpHvX",
          sub_category: "YSBqJpUYejSk",
          price: 120032,
          product_description:
            "For orders that require pick up, information for pickup modalities will be sent to your email.",
          product_suggestion: ["9MQ7aAP2iqJi", "j9pVxA2WpHvX"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "5PfiatGbjrKR",
          order_id: "erracrappes",
          product_name: "Latitude 6320",
          category: "j9pVxA2WpHvX",
          sub_category: "kFrcxhfwwPUn",
          price: 901000,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["9MQ7aAP2iqJi", "FCzoWfyupkiH"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "Crag8WKJhsKq",
          order_id: "uepaaserase",
          product_name: "Women’s bag",
          category: "9MQ7aAP2iqJi",
          sub_category: "w2QRxWg37NGM",
          price: 55432,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["hGA9m8zAXmCo", "FCzoWfyupkiH"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "XMVyvRdvZpCX",
          order_id: "ueppseeerea",
          product_name: "HP Desktop 32’",
          category: "j9pVxA2WpHvX",
          sub_category: "VCTaJRapumqk",
          price: 32120,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["hGA9m8zAXmCo", "FCzoWfyupkiH"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "uDVPw2mft65e",
          order_id: "seesuarceer",
          product_name: "Camon 16Plus",
          category: "o67pbTLMMT5c",
          sub_category: "MZKU3GMKqrTQ",
          price: 60000,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["9MQ7aAP2iqJi", "o67pbTLMMT5c", "WDHsYaBNz886"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "G3rTyNyYy9BM",
          order_id: "upuccaserpp",
          product_name: "Cap Rice",
          category: "2vok2L7ysXpJ",
          sub_category: "sJvYmLcwxgVe",
          price: 222111,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["o67pbTLMMT5c", "9MQ7aAP2iqJi"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "FvPubUKviLfv",
          order_id: "rrepescaurp",
          product_name: "New Jersey Fabric",
          category: "FCzoWfyupkiH",
          sub_category: "zWRwngq53RRN",
          price: 12000,
          product_description:
            "Full-size, textured keyboard with numeric keypad; Touchpad with multi-touch gesture support;",
          product_suggestion: ["hGA9m8zAXmCo", "9MQ7aAP2iqJi"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "Odumosu Street, Ketu 105102, Lagos, Nigeria",
          user_address_city: " Ketu 105102",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "k2yw9Wq4bTZp",
          order_id: "eauurceraec",
          product_name: "Laptop Bag",
          category: "9MQ7aAP2iqJi",
          sub_category: "KZ3mKJ6QcpTL",
          price: 23000,
          product_description:
            "Intel® Core™ i3-1005G1 with Intel® UHD Graphics (1.2 GHz base frequency, up to 3.4 GHz with Intel® Turbo Boost Technology, 4 MB L3cache, 2 cores)",
          product_suggestion: ["o67pbTLMMT5c", "hGA9m8zAXmCo"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "1 Stockton St Union Square, San Francisco",
          user_address_city: "Union Square",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
        {
          product_id: "mEV9xzf4EAzs",
          order_id: "urruecurcar",
          product_name: "Dell Latitude E6322",
          category: "hGA9m8zAXmCo",
          sub_category: "dFfXkLwPyrHD",
          price: 1200,
          product_description: "Random desc",
          product_suggestion: ["o67pbTLMMT5c", "9MQ7aAP2iqJi"],
          product_condition: "fairly_used",
          product_status: "3",
          user_id: "9344639296",
          user_address: "1 Stockton St Union Square, San Francisco",
          user_address_city: "Union Square",
          user_address_lat: 6.5912819,
          user_address_long: 3.3980794,
          upload_price: 100,
        },
      ],
      {}
    );
  },

  down: async ({ queryInterface }: { queryInterface: QueryInterface }) => {
    await queryInterface.bulkDelete("Product", {}, {});
  },
};
